### ISSUE TITLE
how to transprancy the background ?

### ISSUE THREAD

**Issue by VegetableWithChicken** [daktronics/cef-mixer#23]
if using settings ,it can do??

**Comment by avail** [comment]
```css
body {
    background: transparent;
}
```

you will have to do this for every element you want to be transparent.
